### ISSUE TITLE
tickMeter does not start

### ISSUE THREAD

**Issue by Soad999** [xHeaven/tickMeter#1]
Hello,
I wanna use this but when I start tickMeter.exe nothing happens (no error message, nothing but just a small loading on the cursor and that's it.)
I have:
-WinPCAP installed (and rebooted after)
-RTSS installed (fps overlay is working fine)
-tried various versions of tickMeter same happens
-fresh windows 10 x64, but it's up do date
-checked .net framework, whenever I want to install any version it says I have the same or newer.

Any ideas? :)

Thank you!

**Comment by xHeaven** [comment]
Hello,

Do you have the "tickMeter.exe" and the DLL files in the same directory?
Which version did you use? (the release, or you built your own binary?)

Thanks for your answer in advance.

**Comment by xHeaven** [comment]
Hey,

do you have Discord or something like that? I'd like to check what is causing the problem, but since it's working on my computer, and you get zero informations/errors, it's pretty hard like this.
If we could talk faster on a better platform, that would be awesome.

Let me know.

**Comment by xHeaven** [comment]
Hey,

nice! Please, add me, and drop me a PM.

xHeaven#2143
