### ISSUE TITLE
Tickrate is rounded down to 61

### ISSUE THREAD

**Issue by Smagjus** [xHeaven/tickMeter#3]
The update 19 released to the testservers today allows for higher tickrates up to 120. Please take this into account:
https://www.reddit.com/r/PUBATTLEGROUNDS/comments/93qe3l/pubg_update_19_server_tick_rate_was_increased_to/

**Comment by xHeaven** [comment]
Yes, I already noticed it, I'll push out an update as soon as possible. Thanks!
