### ISSUE TITLE
Ping the actual AWS site where the server is hosted

### ISSUE THREAD

**Issue by BattleNonSense** [xHeaven/tickMeter#4]
AWS instances do not respond to ICMP, which is why you can't ping the gameserver directly, however you can get a 100% accurate ping to the server by:

1. looking up the remote name of the gameserver: nslookup 18.130.109.57
which gives you ec2-18-130-109-57.eu-west-2.compute.amazonaws.com
2. then: ping ec2.eu-west-2.amazonaws.com and you get the ping to that specific AWS datacenter. :)

**Comment by xHeaven** [comment]
Oh, wow, glad to see You here, BattleNonSense! :) That's a pretty good idea, thanks. Probably I'll implement this in the next update.

**Comment by BattleNonSense** [comment]
Sadly things seem more complex now because the last 10 servers that I was placed on were hosted by "servers.com", not AWS. O.o
Seems like they either added that hoster or switched to that hoster.

**Comment by xHeaven** [comment]
Yeah, I noticed this change too, looks like they are hosting with the UK2 Group right now. [servers.com, midphase.com, uk2.net]
We will see what we can do, I'll push out a big update in a few days.

Thanks for notifying me anyways! :)
