### ISSUE TITLE
Why is the udp port between 6999 and 7999?

### ISSUE THREAD

**Issue by jeremychiong** [xHeaven/tickMeter#6]
I saw you use the udp port as the condition for the  judgment of pubg server packet, Is it trusted？

**Comment by xHeaven** [comment]
PUBG is using ports between these two values, so it's kinda pointless to check other ports. 

Anyways, since PUBG now has it's own packet-and pingmeter, the whole project is kinda pointless. Maybe it's okay-ish for learning purposes, but even the code is a bit messy.

**Comment by jeremychiong** [comment]
Thank you for answering me, I am very interested in it`s own pingmeter, do you have any idea about the method？At first I thought your method was very similar to pubg. 
Is there any feature I can find by wireshark?
